- hosts: localhost
  become: no
  vars:
    apt:
      repositories:
        - ppa:neovim-ppa/stable
      packages:
        - curl
        - git
        - less
        - python-pip
        - python3
        - python3-pip
        - tmux
        - neovim
    pip2:
      packages:
        - pynvim
    pip3:
      packages:
        - pynvim
        - python-language-server
        - flake8
        - flake8-import-order
        - autopep8
        - isort
        - yapf
        - vim-vint
    anyenv: []

  roles:
    - { role: apt, become: yes }
    - anyenv
    - { role: pip, become: yes }
