- hosts: localhost
  become: no
  vars:
    apt:
      repositories:
        - ppa:neovim-ppa/stable
      packages:
        - software-properties-common
        - bash-completion
        - curl
        - git
        - less
        - python-pip
        - python3
        - python3-pip
        - tmux
        - neovim
        - zip
    pip2:
      packages:
        - pynvim
    pip3:
      packages:
        - pynvim
        - python-language-server
        - flake8
        - flake8-import-order
        - autopep8
        - isort
        - yapf
        - vim-vint
        - pipenv
    anyenv: []
    go:
      packages:
        - org: peco
          project: peco
          version: v0.5.3
          binary: peco
          ftype: tar.gz
        - org: motemen
          project: ghq
          version: v0.12.3
          binary: ghq
          ftype: zip
  roles:
    - { role: apt, become: yes }
    - anyenv
    - { role: pip, become: yes }
    - { role: linux, become: yes }
