[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle', 'NERDTreeFind']
hook_add = '''
    nnoremap <silent> <Leader>nn :<C-u>NERDTreeToggle<CR>
    nnoremap <silent> <Leader>nf :<C-u>NERDTreeFind %<CR>
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = [
    'python',
    'vim',
]
hook_source = '''
    source ~/.config/nvim/plugins/ale.vim
'''

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = ['TagbarToggle']
hook_add = '''
    nnoremap <Leader>t :<C-u>TagbarToggle<CR>
    let g:tagbar_sort = 0
    let g:tagbar_case_insensitive = 1
    let g:tagbar_compact = 1
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
on_ft = [
    'python',
    'go',
]
hook_source = '''
    source ~/.config/nvim/plugins/LanguageClient-neovim.vim
'''
