---
- name: check binary existence
  stat:
    path: /usr/local/bin/{{ pkg.binary }}
  register: result

- name: Download archive
  get_url:
    url: https://github.com/{{ pkg.org }}/{{ pkg.project }}/releases/download/{{ pkg.version }}/{{ pkg.project }}_linux_amd64.{{ pkg.ftype }}
    dest: /tmp/{{ pkg.project }}_linux_amd64.{{ pkg.ftype }}
  when: not result.stat.exists

- name: Extract archive
  unarchive:
    src: /tmp/{{ pkg.project }}_linux_amd64.{{ pkg.ftype }}
    dest: /tmp
  when: not result.stat.exists

- name: Copy binary
  copy:
    src: /tmp/{{ pkg.project }}_linux_amd64/{{ pkg.binary }}
    dest: /usr/local/bin/{{ pkg.binary }}
    remote_src: yes
    mode: preserve

- name: Delete downloaded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/{{ pkg.project }}_linux_amd64
    - /tmp/{{ pkg.project }}_linux_amd64.{{ pkg.ftype }}
