---
- name: "update homebrew"
  homebrew:
    update_homebrew: yes

- name: "add tap repositories"
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew.repositories }}"

- name: "install homebrew packages"
  homebrew:
    name: "{{ homebrew.packages }}"
    state: present

- name: "install homebrew packages with options"
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options }}"
    state: present
  with_items: "{{ homebrew.packages_with_options }}"

- name: "install homebrew cask packages"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew.cask_packages }}"
