---
- name: "update homebrew"
  homebrew:
    update_homebrew: yes

- name: "add tap repositories"
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew.repositories }}"

- name: "install homebrew packages"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew.packages }}"

- name: "install homebrew cask packages"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew.cask_packages }}"
