---
- name: "create git config"
  template:
    src: templates/_gitconfig
    dest: ~/.gitconfig
    force: no

- name: "add bash to /etc/shells"
  template:
    src: templates/shells
    dest: /etc/shells
    force: no
    become: yes
