- name: "add repositories"
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt.repositories }}"

- name: "update cache"
  apt:
    update_cache: yes

- name: "install apt packages"
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt.packages }}"
